# Generated by Django 3.2 on 2021-08-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='address',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='listing',
            name='ac_type',
            field=models.CharField(default='Split AC', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='air_control',
            field=models.TextField(blank=True, default='Air Flow 5400'),
        ),
        migrations.AddField(
            model_name='listing',
            name='btu',
            field=models.DecimalField(decimal_places=1, default=1200, max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='cooling_speed',
            field=models.CharField(default='Turbo and Max Speed Cooling', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='energy_efficient',
            field=models.CharField(default='Inverter', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='fan_speed',
            field=models.CharField(default='Multi Fan Speeds and Wide Angel Louvers', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='remote_control',
            field=models.CharField(default='YES', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='temperature_adjustment',
            field=models.CharField(default='AUTO', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='timer',
            field=models.CharField(default='YES', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='ton',
            field=models.IntegerField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(default=None),
        ),
    ]
